config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :users,         only: %i[ index new create ] do
    resource :backlog,      only: %i[ show ] do
      post "add_game/:game_id", to: "backlogs#add_game", as: "add_game"
      delete "remove_game/:game_id", to: "backlogs#remove_game", as: "remove_game"
    end
    resources :lists,       only: %i[ index show ]
    get "stats", to: "user_stats#show"
  end
  resources :user_sessions, only: %i[ new create destroy ]
  resources :games,         only: %i[ index show ] do
    resources :ratings,       only: %i[ create update destroy ]
    resource  :favorites,     only: %i[ create destroy ]
  end
  resources :companies,     only: %i[ index show ]
  get "search", to: "search#index"

  # Defines the root path route ("/")
  root "games#index"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :check_query, only: :index
  def index
    if sanitized_query.present?
      @games = IgdbService.instance.game_search(sanitized_query)
    else
      @games = Game.none
    end
  end

  private

  def check_query
    if sanitized_query.blank?
      flash[:alert] = "You must provide a search query."
      redirect_to root_path
    end
  end

  def sanitized_query
    if params[:query].present?
      ActiveRecord::Base.sanitize_sql_like(params[:query])
    end
  end
end

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :get, local: true, id: "search-form") do %>
    <div class="form-group">
        <%= text_field_tag :query, params[:query], placeholder: "Search for a game", class: "form-control", autofocus: true %>
    </div>
    <%= submit_tag "Search" %>
<% end %>

app/views/search/index.html.erb
<h1>Search Results</h1>

<% if @games.present? %>
  <h2><%= "#{pluralize(@games.count, "Game")}" %> found.</h2>
  <ul>
    <% @games.each do |game| %>
      <li><%= link_to "#{game.name} (#{Platform.where(id: game.platforms).pluck(:name).join(', ')})", game_path(game.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

<%= link_to "Home", root_path %>