config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :users,         only: %i[ index new create ] do
    resource :backlog,      only: %i[ show ] do
      post "add_game/:game_id", to: "backlogs#add_game", as: "add_game"
      delete "remove_game/:game_id", to: "backlogs#remove_game", as: "remove_game"
    end
    resources :lists,       only: %i[ index show ]
    get "stats", to: "user_stats#show"
  end
  resources :user_sessions, only: %i[ new create destroy ]
  resources :games,         only: %i[ index show ] do
    resources :ratings,       only: %i[ create update destroy ]
    resource  :favorites,     only: %i[ create destroy ]
  end
  resources :companies,     only: %i[ index show ]
  get "search", to: "search#index"

  # Defines the root path route ("/")
  root "games#index"
end

app/models/game.rb
class Game < ApplicationRecord
  validates :id, presence: true,
                 uniqueness: true,
                 numericality: { only_integer: true }
  validates :name, presence: true

  has_and_belongs_to_many :backlogs
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies

  has_many :developers, -> { merge(InvolvedCompany.developers) },
                             through: :involved_companies,
                             source: :company

  has_many :publishers, -> { merge(InvolvedCompany.publishers) },
                             through: :involved_companies,
                             source: :company

  has_many :ported_by,  -> { merge(InvolvedCompany.porting) },
                             through: :involved_companies,
                             source: :company

  has_many :supporting_companies, -> { merge(InvolvedCompany.supporting) },
                                       through: :involved_companies,
                                       source: :company

  has_many :ratings,   as: :rateable,    dependent: :destroy
  has_many :favorites, as: :favoritable, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user
  has_many :list_games
  has_many :lists, through: :list_games

  default_scope { order(:name) }

  def first_release_date
    Time.at(read_attribute(:first_release_date)).in_time_zone.to_datetime if first_release_date_present?
  end

  def first_release_date_present?
    read_attribute(:first_release_date).present?
  end

  private

  # Protect this association from being called directly; it's really
  # only useful as a :through table for setting up the more friendly
  # developers/publishers/etc associations
  def involved_companies
    super
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @letter = params[:letter]

    if @letter
      @games = Game.includes(:platforms, :genres).where("name LIKE ?", "#{@letter}%")
    else
      @games = Game.includes(:platforms, :genres).all
    end
  end

  def show
    @game = Game.find_by(id: params[:id])

    if @game.nil?
      ActiveRecord::Base.transaction do
        ::Importers::Game.new.import_by_ids(params[:id])
        @game = Game.find(params[:id])
      end
    end
  end
end

app/views/games/_alphabet_nav.html.erb
<div id="alphabet-container">
  <nav id="alphabet-nav">
    <ul>
      <% ("A".."Z").each do |letter| %>
        <li>
          <%= link_to letter.upcase, games_path(letter: letter) %>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/games/index.html.erb
<%= form_with url: games_path, method: :get, local: false, data: { controller: "search" } do %>
  <%= text_field_tag :query, nil, placeholder: "Search for games...", data: { action: "input->search#update" } %>
<% end %>

<div id="search-results" data-controller="results"></div>
<h1>Gamez</h1>
<%= render "alphabet_nav" %>
<% if @games.load.present? %>
  <ol>
  <% @games.each do |game| %>
    <li><%= link_to "#{game.name} (#{game.platforms.pluck(:name).join(', ')})", game_path(game) %></li>
  <% end %>
  </ol>
<% else %>
  <p>No games found.  Perhaps you forgot to import some?</p>
<% end %>

app/views/games/show.html.erb
<h1><%= @game.name %></h1>
<% if @game.first_release_date.present? %>
  <h5>First released: <%= @game.first_release_date.strftime('%A, %d %b %Y') %></h5>
<% end %>

<% if current_user %>
  <%= render "ratings/form", rateable: @game %>
  <% if current_user.backlog.games.include?(@game) %>
    <%= button_to "Remove from backlog", remove_game_user_backlog_path(current_user, @game), method: :delete %>
  <% else %>
    <%= button_to "Add to backlog", add_game_user_backlog_path(current_user, @game), method: :post %>
  <% end %>

  <% if current_user.favorited?(@game) %>
    <%= button_to "Unfavorite", game_favorites_path(@game), method: :delete %>
  <% else %>
    <%= button_to "Favorite", game_favorites_path(@game), method: :post %>
  <% end %>
<% end %>

<p>Genres: <%= @game.genres.pluck(:name).join(", ") %></p>
<p>Platforms: <%= @game.platforms.pluck(:name).join(", ") %></p>
<p>Summary: <%= @game.summary %></p>

<% if @game.developers.present? %>
  <h3>Developers:</h3>
  <ul>
    <% @game.developers.each do |developer| %>
      <li><%= link_to "#{developer.name}", company_path(developer) %></li>
    <% end %>
  </ul>
<% end %>

<% if @game.publishers.present? %>
  <h3>Publishers:</h3>
  <ul>
    <% @game.publishers.each do |publisher| %>
      <li><%= link_to "#{publisher.name}", company_path(publisher) %></li>
    <% end %>
  </ul>
<% end %>

<% if @game.ported_by.present? %>
  <h3>Ported By:</h3>
  <ul>
    <% @game.ported_by.each do |porter| %>
      <li><%= link_to "#{porter.name}", company_path(porter) %></li>
    <% end %>
  </ul>
<% end %>

<% if @game.supporting_companies.present? %>
  <h3>Supporting Companies:</h3>
  <ul>
    <% @game.supporting_companies.each do |supporting_company| %>
      <li><%= link_to "#{supporting_company.name}", company_path(supporting_company) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Home", root_path %>