config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :users,         only: %i[ index new create ] do
    resource :backlog,      only: %i[ show ] do
      post "add_game/:game_id", to: "backlogs#add_game", as: "add_game"
      delete "remove_game/:game_id", to: "backlogs#remove_game", as: "remove_game"
    end
    resources :lists,       only: %i[ index show ]
    get "stats", to: "user_stats#show"
  end
  resources :user_sessions, only: %i[ new create destroy ]
  resources :games,         only: %i[ index show ] do
    resources :ratings,       only: %i[ create update destroy ]
    resource  :favorites,     only: %i[ create destroy ]
  end
  resources :companies,     only: %i[ index show ]
  get "search", to: "search#index"

  # Defines the root path route ("/")
  root "games#index"
end

app/models/company.rb
class Company < ApplicationRecord
  validates  :id, presence: true,
                 uniqueness: true,
                 numericality: { only_integer: true }
  validates  :name, presence: true

  belongs_to :parent,
              class_name: Company.name,
              optional: true

  has_many   :companies,
              class_name: Company.name,
              foreign_key: :parent_id,
              dependent: :nullify

  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies

  has_many :developed_games, -> { merge(InvolvedCompany.developers) },
                                  through: :involved_companies,
                                  source: :game

  has_many :published_games, -> { merge(InvolvedCompany.publishers) },
                                  through: :involved_companies,
                                  source: :game

  has_many :ported_games,    -> { merge(InvolvedCompany.porting) },
                                  through: :involved_companies,
                                  source: :game

  has_many :game_contributions, -> { merge(InvolvedCompany.supporting) },
                                     through: :involved_companies,
                                     source: :game

  default_scope { order(:name) }
  private

  # Protect this association from being called directly; similar to
  # the equivalent association in Game.rb, this is only really useful
  # as a :through table.
  def involved_companies
    super
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/views/companies/index.html.erb
<% if @companies.load.present? %>
  <h1>Companiez</h1>
  <ul>
  <% @companies.each do |company| %>
    <li><%= link_to "#{company.name}", company_path(company) %></li>
  <% end %>
  </ul>
<% else %>
  <p>No companies found.  Perhaps you forgot to import some?</p>
<% end %>

<%= link_to "Home", root_path %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<% if @company.parent.present? %>\
  <h3>Parent Company:</h3>
  <%= link_to "#{@company.parent.name}", company_path(@company.parent) %>
<% end %>

<% if @company.developed_games.present? %>
  <h3>Developed Games:</h3>
  <ul>
    <% @company.developed_games.each do |game| %>
      <li><%= link_to "#{game.name}", game_path(game)%></li>
    <% end %>
  </ul>
<% end %>

<% if @company.published_games.present? %>
  <h3>Published Games:</h3>
  <ul>
    <% @company.published_games.each do |game| %>
      <li><%= link_to "#{game.name}", game_path(game) %></li>
    <% end %>
  </ul>
<% end %>

<% if @company.ported_games.present? %>
  <h3>Ported Games:</h3>
  <ul>
    <% @company.ported_games.each do |game| %>
      <li><%= link_to "#{game.name}", game_path(game) %></li>
    <% end %>
  </ul>
<% end %>

<% if @company.game_contributions.present? %>
  <h3>Other Contributions:</h3>
  <ul>
    <li><%= link_to "#{game.name}", game_path(game) %></li>
  </ul>
<% end %>

<h5>Navigation:</h5>
<ul>
  <li><%= link_to "Other Companies", companies_path %></li>
  <li><%= link_to "Home", root_path %></li>
</ul>