config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :users,         only: %i[ index new create ] do
    resource :backlog,      only: %i[ show ] do
      post "add_game/:game_id", to: "backlogs#add_game", as: "add_game"
      delete "remove_game/:game_id", to: "backlogs#remove_game", as: "remove_game"
    end
    resources :lists,       only: %i[ index show ]
    get "stats", to: "user_stats#show"
  end
  resources :user_sessions, only: %i[ new create destroy ]
  resources :games,         only: %i[ index show ] do
    resources :ratings,       only: %i[ create update destroy ]
    resource  :favorites,     only: %i[ create destroy ]
  end
  resources :companies,     only: %i[ index show ]
  get "search", to: "search#index"

  # Defines the root path route ("/")
  root "games#index"
end

app/views/layouts/_footer.html.erb
<div id="footer-container">
  <p>Data sourced from <a href="https://igdb.com">IGDB</a></p>
</div>

app/views/layouts/_nav.html.erb
<nav id="main-nav">
    <div>
      <%= link_to "Home", root_path %>
    </div>
    <%= render "search/form" %>
    <div id="user-links">
      <% if current_user.present? %>
          <p>Hello, <%= current_user.name %></p>
          <%= link_to "Stats", user_stats_path(current_user) %>
          <%= link_to "Backlog", user_backlog_path(current_user) %>
          <%= link_to "Lists", user_lists_path(current_user) %>
          <%= link_to "Log Out", user_session_path(current_user), data: { turbo_method: :delete } %><br>
      <% else %>
          <%= link_to "Login", new_user_session_path %><br>
      <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Quest Warden" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>">
          <%= message %>
        </div>
      <% end %>
      
      <%= render "layouts/nav" %>
    </header>

    <main>
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>